---
name: PR Checks

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          make init
          make deps
          echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Check code formatting
        run: make format

      - name: Lint code
        run: make lint

      - name: Run Unit Tests
        run: make test
